[shiba6v]
feed_url = "http://shiba6v.hatenablog.com/feed"

[camphor-tech]
feed_url = "https://tech.camph.net/feed/"

[tomoyat1]
feed_url = "https://blog.tomoyat1.com/rss"

[dora1998]
feed_url = "https://feed-api.minoru.dev/rss"

[marty954]
feed_url = "http://skstmrty.hatenablog.com/feed"

[KMConner]
feed_url = "https://blog.kmconner.net/rss"

[aratasato]
feed_url = "https://ataran.hatenablog.com/feed"

[plus_kyoto]
feed_url = "https://blog-api.naoki.dev/rss"
